const HEAD_IMG = "HEAD_IMG";
const HEAD_TEXT = "HEAD_TEXT";
const HEAD_LINK = "HEAD_LINK";

const TABO_STATE = "TABO_STATE";
const INIT_TABO_LIST = "INIT_TABO_LIST";
const ADD_TABO_LIST = "ADD_TABO_LIST";

const TABT_STATE = "TABT_STATE";
const INIT_TABT_LIST = "INIT_TABT_LIST";
const ADD_TABT_LIST = "ADD_TABT_LIST";

const TABS_STATE = "TABS_STATE";
const INIT_TABS_LIST = "INIT_TABS_LIST";
const ADD_TABS_LIST = "ADD_TABS_LIST";

const DETA_PAGE_DATA = "DETA_PAGE_DATA";

export default {
	HEAD_IMG,
	HEAD_TEXT,
	HEAD_LINK,
	TABO_STATE,
	INIT_TABO_LIST,
	ADD_TABO_LIST,
	TABT_STATE,
	INIT_TABT_LIST,
	ADD_TABT_LIST,
	TABS_STATE,
	INIT_TABS_LIST,
	ADD_TABS_LIST,
	DETA_PAGE_DATA
}